# -*- coding: utf-8 -*-
"""BRAINTUMORDETECTION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntLh97RUP7rq81OqUykU35_65DzK0FJp
"""

import zipfile, os
from google.colab import files

# Step 1: Upload dataset ZIP
uploaded = files.upload()

# Step 2: Extract dataset
for fname in uploaded.keys():
    with zipfile.ZipFile(fname, 'r') as zip_ref:
        zip_ref.extractall("/content/Brain_MRI_Dataset")
DATA_DIR = "/content/Brain_MRI_Dataset"

print("Dataset extracted to:", DATA_DIR)
print("Classes:", os.listdir(DATA_DIR))

# ============================================================
# 🧠 Brain MRI Tumor Detection Pipeline
# Fuzzy → U-Net → ROI Extraction → SSBTCNet
# ============================================================

import os, random
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, optimizers
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# CONFIG
# -----------------------------
SEED = 42
tf.random.set_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

TRAIN_DIR = "/content/Brain_MRI_Dataset/BT-MRI Dataset/BT-MRI Dataset/Training"
TEST_DIR  = "/content/Brain_MRI_Dataset/BT-MRI Dataset/BT-MRI Dataset/Testing"

IMG_SIZE = (128, 128)
BATCH_SIZE = 8
NUM_CLASSES = 4
EPOCHS = 30

CLASS_NAMES = sorted(os.listdir(TRAIN_DIR))

# -----------------------------
# FUZZY IMAGE ENHANCEMENT FUNCTION
# -----------------------------
def fuzzy_enhance(img):
    """Enhance contrast using fuzzy logic approach."""
    img = cv2.equalizeHist((img*255).astype(np.uint8))
    img = img / 255.0
    return img[..., np.newaxis]

# -----------------------------
# DATA LOADING
# -----------------------------
def load_dataset(data_dir, enhance=True):
    images, labels = [], []
    class_map = {cls:i for i, cls in enumerate(CLASS_NAMES)}
    for cls in CLASS_NAMES:
        cls_folder = os.path.join(data_dir, cls)
        for img_file in os.listdir(cls_folder):
            img_path = os.path.join(cls_folder, img_file)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, IMG_SIZE)
            if enhance:
                img = fuzzy_enhance(img)
            images.append(img)
            labels.append(class_map[cls])
    return np.array(images), np.array(labels)

X_train, y_train = load_dataset(TRAIN_DIR)
X_test, y_test = load_dataset(TEST_DIR)

print("✅ Data loaded:", X_train.shape, y_train.shape, X_test.shape, y_test.shape)

# -----------------------------
# U-NET SEGMENTATION
# -----------------------------
def unet_model(input_size=(128,128,1)):
    inputs = layers.Input(input_size)
    # Encoder
    c1 = layers.Conv2D(16, (3,3), activation='relu', padding='same')(inputs)
    c1 = layers.Conv2D(16, (3,3), activation='relu', padding='same')(c1)
    p1 = layers.MaxPooling2D((2,2))(c1)

    c2 = layers.Conv2D(32, (3,3), activation='relu', padding='same')(p1)
    c2 = layers.Conv2D(32, (3,3), activation='relu', padding='same')(c2)
    p2 = layers.MaxPooling2D((2,2))(c2)

    c3 = layers.Conv2D(64, (3,3), activation='relu', padding='same')(p2)
    c3 = layers.Conv2D(64, (3,3), activation='relu', padding='same')(c3)
    p3 = layers.MaxPooling2D((2,2))(c3)

    # Bottleneck
    c4 = layers.Conv2D(128, (3,3), activation='relu', padding='same')(p3)
    c4 = layers.Conv2D(128, (3,3), activation='relu', padding='same')(c4)

    # Decoder
    u5 = layers.UpSampling2D((2,2))(c4)
    u5 = layers.concatenate([u5, c3])
    c5 = layers.Conv2D(64, (3,3), activation='relu', padding='same')(u5)
    c5 = layers.Conv2D(64, (3,3), activation='relu', padding='same')(c5)

    u6 = layers.UpSampling2D((2,2))(c5)
    u6 = layers.concatenate([u6, c2])
    c6 = layers.Conv2D(32, (3,3), activation='relu', padding='same')(u6)
    c6 = layers.Conv2D(32, (3,3), activation='relu', padding='same')(c6)

    u7 = layers.UpSampling2D((2,2))(c6)
    u7 = layers.concatenate([u7, c1])
    c7 = layers.Conv2D(16, (3,3), activation='relu', padding='same')(u7)
    c7 = layers.Conv2D(16, (3,3), activation='relu', padding='same')(c7)

    outputs = layers.Conv2D(1, (1,1), activation='sigmoid')(c7)
    model = models.Model(inputs, outputs)
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# -----------------------------
# SSBTCNet CLASSIFIER
# -----------------------------
def ssbtcnet_model(input_shape=(128,128,1), num_classes=NUM_CLASSES):
    model = models.Sequential([
        layers.Conv2D(32,(3,3),activation='relu',input_shape=input_shape),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(64,(3,3),activation='relu'),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(128,(3,3),activation='relu'),
        layers.MaxPooling2D((2,2)),
        layers.Flatten(),
        layers.Dense(128,activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(num_classes,activation='softmax')
    ])
    model.compile(optimizer=optimizers.Adam(1e-4),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

# -----------------------------
# ROI EXTRACTION FUNCTION
# -----------------------------
def extract_roi(images, masks):
    rois = []
    for img, mask in zip(images, masks):
        mask = (mask > 0.1).astype(np.uint8)
        contours, _ = cv2.findContours(mask[:,:,0], cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if contours:
            x, y, w, h = cv2.boundingRect(max(contours, key=cv2.contourArea))
            roi = img[y:y+h, x:x+w]
            roi = cv2.resize(roi, IMG_SIZE)
            rois.append(roi)
        else:
            rois.append(cv2.resize(img, IMG_SIZE))
    return np.array(rois)

# -----------------------------
# SEGMENTATION MASK GENERATION
# -----------------------------
unet = unet_model()
# Save the U-Net model
unet.save("unet_model.keras")

# Train U-Net for real segmentation if masks exist
# For demo, using fuzzy thresholding as mask
X_train_masks = (X_train > 0.1).astype(np.float32)
X_test_masks = (X_test > 0.1).astype(np.float32)

# Extract ROI from U-Net masks
X_train_roi = extract_roi(X_train, X_train_masks)
X_test_roi = extract_roi(X_test, X_test_masks)

# -----------------------------
# TRAIN SSBTCNet ON ROI
# -----------------------------
classifier = ssbtcnet_model()
cb_list = [
    callbacks.ModelCheckpoint("best_model.keras", monitor="val_accuracy", save_best_only=True, mode="max"),
    callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.3, patience=3, verbose=1),
    callbacks.EarlyStopping(monitor="val_loss", patience=6, restore_best_weights=True)
]

history = classifier.fit(
    X_train_roi, y_train,
    validation_split=0.2,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=cb_list
)

# -----------------------------
# EVALUATION
# -----------------------------
classifier.load_weights("best_model.keras")
test_loss, test_acc = classifier.evaluate(X_test_roi, y_test)
print(f"✅ Test Accuracy: {test_acc*100:.2f}%")

preds = classifier.predict(X_test_roi)
pred_classes = np.argmax(preds, axis=1)

# Classification report
print("\n📊 Classification Report:")
print(classification_report(y_test, pred_classes, target_names=CLASS_NAMES))

# Confusion matrix
cm = confusion_matrix(y_test, pred_classes)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
plt.title("🧩 Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Training curves
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], marker='o', label='Train Accuracy')
plt.plot(history.history['val_accuracy'], marker='o', label='Val Accuracy')
plt.title('📈 Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1,2,2)
plt.plot(history.history['loss'], marker='o', label='Train Loss')
plt.plot(history.history['val_loss'], marker='o', label='Val Loss')
plt.title('📉 Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

"""**Note**: Please ensure you have run the previous code cell (cell `ZSXQkovOiTnr`) before executing this cell, as it calculates the confusion matrix (`cm`) used in this section."""

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

# Rename the uploaded file to sample_mri.jpg if it's not already
if 'sample_mri.jpg' not in uploaded.keys():
  for fn in uploaded.keys():
    # Assuming the user uploads only one file if the name is different
    !mv "{fn}" /content/sample_mri.jpg
    print(f"Renamed '{fn}' to 'sample_mri.jpg'")

# ============================================================
# 🧠 Brain MRI Tumor Detection Pipeline
# Fuzzy → U-Net → ROI Extraction → SSBTCNet
# ============================================================

import os, random
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, optimizers
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, precision_recall_curve
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# CONFIG
# -----------------------------
SEED = 42
tf.random.set_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

TRAIN_DIR = "/content/Brain_MRI_Dataset/BT-MRI Dataset/BT-MRI Dataset/Training"
TEST_DIR  = "/content/Brain_MRI_Dataset/BT-MRI Dataset/BT-MRI Dataset/Testing"

IMG_SIZE = (128, 128)
BATCH_SIZE = 8
NUM_CLASSES = 4
EPOCHS = 30

CLASS_NAMES = sorted(os.listdir(TRAIN_DIR))

# -----------------------------
# FUZZY IMAGE ENHANCEMENT FUNCTION
# -----------------------------
def fuzzy_enhance(img):
    """Enhance contrast using fuzzy logic approach."""
    img = cv2.equalizeHist((img*255).astype(np.uint8))
    img = img / 255.0
    return img[..., np.newaxis]

# -----------------------------
# DATA LOADING
# -----------------------------
def load_dataset(data_dir, enhance=True):
    images, labels = [], []
    class_map = {cls:i for i, cls in enumerate(CLASS_NAMES)}
    for cls in CLASS_NAMES:
        cls_folder = os.path.join(data_dir, cls)
        for img_file in os.listdir(cls_folder):
            img_path = os.path.join(cls_folder, img_file)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, IMG_SIZE)
            if enhance:
                img = fuzzy_enhance(img)
            images.append(img)
            labels.append(class_map[cls])
    return np.array(images), np.array(labels)

X_train, y_train = load_dataset(TRAIN_DIR)
X_test, y_test = load_dataset(TEST_DIR)

print("✅ Data loaded:", X_train.shape, y_train.shape, X_test.shape, y_test.shape)

# -----------------------------
# U-NET SEGMENTATION
# -----------------------------
def unet_model(input_size=(128,128,1)):
    inputs = layers.Input(input_size)

    # Encoder
    c1 = layers.Conv2D(16, (3,3), activation='relu', padding='same')(inputs)
    c1 = layers.Conv2D(16, (3,3), activation='relu', padding='same')(c1)
    p1 = layers.MaxPooling2D((2,2))(c1)

    c2 = layers.Conv2D(32, (3,3), activation='relu', padding='same')(p1)
    c2 = layers.Conv2D(32, (3,3), activation='relu', padding='same')(c2)
    p2 = layers.MaxPooling2D((2,2))(c2)

    c3 = layers.Conv2D(64, (3,3), activation='relu', padding='same')(p2)
    c3 = layers.Conv2D(64, (3,3), activation='relu', padding='same')(c3)
    p3 = layers.MaxPooling2D((2,2))(c3)

    # Bottleneck
    c4 = layers.Conv2D(128, (3,3), activation='relu', padding='same')(p3)
    c4 = layers.Conv2D(128, (3,3), activation='relu', padding='same')(c4)

    # Decoder
    u5 = layers.UpSampling2D((2,2))(c4)
    u5 = layers.concatenate([u5, c3])
    c5 = layers.Conv2D(64, (3,3), activation='relu', padding='same')(u5)
    c5 = layers.Conv2D(64, (3,3), activation='relu', padding='same')(c5)

    u6 = layers.UpSampling2D((2,2))(c5)
    u6 = layers.concatenate([u6, c2])
    c6 = layers.Conv2D(32, (3,3), activation='relu', padding='same')(u6)
    c6 = layers.Conv2D(32, (3,3), activation='relu', padding='same')(c6)

    u7 = layers.UpSampling2D((2,2))(c6)
    u7 = layers.concatenate([u7, c1])
    c7 = layers.Conv2D(16, (3,3), activation='relu', padding='same')(u7)
    c7 = layers.Conv2D(16, (3,3), activation='relu', padding='same')(c7)

    outputs = layers.Conv2D(1, (1,1), activation='sigmoid')(c7)
    model = models.Model(inputs, outputs)
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

unet = unet_model()

# Dummy masks (for demo if dataset has no masks)
X_train_masks = (X_train > 0.1).astype(np.float32)
X_test_masks = (X_test > 0.1).astype(np.float32)

# -----------------------------
# ROI EXTRACTION
# -----------------------------
def extract_roi(images, masks):
    rois = []
    for img, mask in zip(images, masks):
        mask = (mask > 0.1).astype(np.uint8)
        contours, _ = cv2.findContours(mask[:,:,0], cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if contours:
            x, y, w, h = cv2.boundingRect(max(contours, key=cv2.contourArea))
            roi = img[y:y+h, x:x+w]
            roi = cv2.resize(roi, IMG_SIZE)
            rois.append(roi)
        else:
            rois.append(cv2.resize(img, IMG_SIZE))
    return np.array(rois)

X_train_roi = extract_roi(X_train, X_train_masks)
X_test_roi = extract_roi(X_test, X_test_masks)

# -----------------------------
# SSBTCNet CLASSIFIER
# -----------------------------
def ssbtcnet_model(input_shape=(128,128,1), num_classes=NUM_CLASSES):
    model = models.Sequential([
        layers.Conv2D(32,(3,3),activation='relu',input_shape=input_shape),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(64,(3,3),activation='relu'),
        layers.MaxPooling2D((2,2)),
        layers.Conv2D(128,(3,3),activation='relu'),
        layers.MaxPooling2D((2,2)),
        layers.Flatten(),
        layers.Dense(128,activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(num_classes,activation='softmax')
    ])
    model.compile(optimizer=optimizers.Adam(1e-4),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

classifier = ssbtcnet_model()

cb_list = [
    callbacks.ModelCheckpoint("best_model.keras", monitor="val_accuracy", save_best_only=True),
    callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.3, patience=3),
    callbacks.EarlyStopping(monitor="val_loss", patience=6, restore_best_weights=True)
]

# -----------------------------
# TRAIN CLASSIFIER
# -----------------------------
history = classifier.fit(
    X_train_roi, y_train,
    validation_split=0.2,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=cb_list
)

classifier.load_weights("best_model.keras")

# -----------------------------
# EVALUATION
# -----------------------------
test_loss, test_acc = classifier.evaluate(X_test_roi, y_test)
print(f"✅ Test Accuracy: {test_acc*100:.2f}%")

preds = classifier.predict(X_test_roi)
pred_classes = np.argmax(preds, axis=1)

# -------------------------
# 1. CONFUSION MATRIX
# -------------------------
cm = confusion_matrix(y_test, pred_classes)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
plt.title("🧩 Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# -------------------------
# 2 & 3. TRAINING CURVES
# -------------------------
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], marker='o')
plt.plot(history.history['val_accuracy'], marker='o')
plt.title("📈 Accuracy Curve")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Train","Val"])
plt.grid(True)

plt.subplot(1,2,2)
plt.plot(history.history['loss'], marker='o')
plt.plot(history.history['val_loss'], marker='o')
plt.title("📉 Loss Curve")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend(["Train","Val"])
plt.grid(True)
plt.show()

# ============================================================
# EXTRA GRAPHS (5 NEW GRAPHS)
# ============================================================

# -------------------------
# 4. CLASS DISTRIBUTION
# -------------------------
plt.figure(figsize=(8,5))
sns.countplot(x=y_train, palette="viridis")
plt.title("🧮 Class Distribution in Training Set")
plt.xlabel("Class Index")
plt.ylabel("Count")
plt.xticks(range(NUM_CLASSES), CLASS_NAMES)
plt.grid(axis='y')
plt.show()

# -------------------------
# 5. ROC CURVES
# -------------------------
y_test_onehot = to_categorical(y_test, NUM_CLASSES)
plt.figure(figsize=(8,6))

for i in range(NUM_CLASSES):
    fpr, tpr, _ = roc_curve(y_test_onehot[:, i], preds[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{CLASS_NAMES[i]} (AUC={roc_auc:.2f})")

plt.plot([0,1],[0,1],'--',color='gray')
plt.title("📈 ROC Curve for Each Class")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid(True)
plt.show()

# -------------------------
# 6. PRECISION–RECALL CURVES
# -------------------------
plt.figure(figsize=(8,6))
for i in range(NUM_CLASSES):
    precision, recall, _ = precision_recall_curve(y_test_onehot[:, i], preds[:, i])
    plt.plot(recall, precision, label=CLASS_NAMES[i])

plt.title("📉 Precision–Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.legend()
plt.grid(True)
plt.show()

# -------------------------
# 7. RANDOM PREDICTION VISUALIZATION
# -------------------------
idx = random.randint(0, len(X_test_roi)-1)

plt.figure(figsize=(5,5))
plt.imshow(X_test_roi[idx].squeeze(), cmap='gray')
plt.title(f"🧠 Predicted: {CLASS_NAMES[pred_classes[idx]]}\n🎯 Actual: {CLASS_NAMES[y_test[idx]]}")
plt.axis('off')
plt.show()

# -------------------------
# 8. ORIGINAL MRI vs MASK vs ROI
# -------------------------
mask = X_test_masks[idx].squeeze()
orig = X_test[idx].squeeze()
roi  = X_test_roi[idx].squeeze()

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(orig, cmap='gray')
plt.title("🖼️ Original MRI")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(mask, cmap='gray')
plt.title("🎯 Segmentation Mask")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(roi, cmap='gray')
plt.title("🔍 Extracted ROI")
plt.axis('off')

plt.show()

